# Generated by Django 2.0.2 on 2020-10-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pregunta', models.CharField(max_length=500)),
                ('contenido_pregunta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pregunta_Categoria'),
        ),
    ]
